export enum SetId {
  ADVENTURES = "adventures",
  ALCHEMY = "alchemy",
  ALLIES = "allies",
  BASE_SET = "baseset",
  BASE_SET_2 = "baseset2",
  BASE_SET_2_ADD = "baseset2add",
  CORNUCOPIA = "cornucopia",
  DARK_AGES = "darkages",
  EMPIRES = "empires",
  GUILDS = "guilds",
  GUILDSCORNUCOPIA = "guildscornucopia",
  GUILDSCORNUCOPIA_2 = "guildscornucopia2",
  GUILDSCORNUCOPIA_2_ADD = "guildscornucopia2add",
  HINTERLANDS = "hinterlands",
  HINTERLANDS_2 = "hinterlands2",
  HINTERLANDS_2_ADD = "hinterlands2add",
  INTRIGUE = "intrigue",
  INTRIGUE_2 = "intrigue2",
  INTRIGUE_2_ADD = "intrigue2add",
  MENAGERIE = "menagerie",
  NOCTURNE = "nocturne",
  PLUNDER = "plunder",
  PROMOS = "promos",
  PROSPERITY = "prosperity",
  PROSPERITY_2 = "prosperity2",
  PROSPERITY_2_ADD = "prosperity2add",
  RENAISSANCE = "renaissance",
  SEASIDE = "seaside",
  SEASIDE_2 = "seaside2",
  SEASIDE_2_ADD = "seaside2add",
  PERSONAL = "personal",
  ALL = "all",
  TO_FORCE_RELOAD = "toforcereload",
}

export const SetOrder: Record<SetId, number> = {
  [SetId.BASE_SET]: 1,
  [SetId.BASE_SET_2_ADD]: 1.1,
  [SetId.BASE_SET_2]: 1.2,
  [SetId.INTRIGUE]: 2,
  [SetId.INTRIGUE_2_ADD]: 2.1,
  [SetId.INTRIGUE_2]: 2.2,
  [SetId.SEASIDE]: 3,
  [SetId.SEASIDE_2_ADD]: 3.1,
  [SetId.SEASIDE_2]: 3.2,
  [SetId.ALCHEMY]: 4,
  [SetId.PROSPERITY]: 5,
  [SetId.PROSPERITY_2_ADD]: 5.1,
  [SetId.PROSPERITY_2]: 5.2,
  [SetId.CORNUCOPIA]: 6,
  [SetId.HINTERLANDS]: 7,
  [SetId.HINTERLANDS_2_ADD]: 7.1,
  [SetId.HINTERLANDS_2]: 7.2,
  [SetId.DARK_AGES]: 8,
  [SetId.GUILDS]: 9,
  // Technically this combined set was released after Plunder, but for sorting
  // purposes we want to put it with the standalone Guild set.
  [SetId.GUILDSCORNUCOPIA]: 9,
  [SetId.ADVENTURES]: 10,
  [SetId.EMPIRES]: 11,
  [SetId.NOCTURNE]: 12,
  [SetId.RENAISSANCE]: 13,
  [SetId.MENAGERIE]: 14,
  [SetId.ALLIES]: 15,
  [SetId.PLUNDER]: 16,
  [SetId.GUILDSCORNUCOPIA_2]: 17,
  [SetId.GUILDSCORNUCOPIA_2_ADD]: 17.1,
  [SetId.PROMOS]: 1_000,
  [SetId.PERSONAL]: 1_0001,
  [SetId.ALL]: 1_002,
  [SetId.TO_FORCE_RELOAD]: 1_003,
};

export const FirstEditionSets: SetId[] = [
  SetId.BASE_SET,
  SetId.INTRIGUE,
  SetId.SEASIDE,
  SetId.PROSPERITY,
  SetId.HINTERLANDS,
  SetId.GUILDS,
  SetId.CORNUCOPIA,
  SetId.GUILDSCORNUCOPIA,
];

export const NotFilterableSets: SetId[] = [
  SetId.PROMOS,
  SetId.PERSONAL,
  SetId.ALL,
  SetId.TO_FORCE_RELOAD,
  SetId.BASE_SET_2_ADD,
  SetId.GUILDSCORNUCOPIA_2_ADD,
  SetId.HINTERLANDS_2_ADD,
  SetId.INTRIGUE_2_ADD,
  SetId.PROSPERITY_2_ADD,
  SetId.SEASIDE_2_ADD,
];

export const SecondEditionSets: SetId[] = [
  SetId.BASE_SET_2,
  SetId.INTRIGUE_2,
  SetId.SEASIDE_2,
  SetId.PROSPERITY_2,
  SetId.HINTERLANDS_2,
  SetId.GUILDSCORNUCOPIA_2,
];

export const FirstToSecondEdition: Map<SetId, SetId> = new Map([
  [SetId.BASE_SET, SetId.BASE_SET_2],
  [SetId.INTRIGUE, SetId.INTRIGUE_2],
  [SetId.SEASIDE, SetId.SEASIDE_2],
  [SetId.PROSPERITY, SetId.PROSPERITY_2],
  [SetId.HINTERLANDS, SetId.HINTERLANDS_2],
  [SetId.GUILDS, SetId.GUILDSCORNUCOPIA_2],
  [SetId.CORNUCOPIA, SetId.GUILDSCORNUCOPIA_2],
  [SetId.GUILDSCORNUCOPIA, SetId.GUILDSCORNUCOPIA_2],
]);
